### ISSUE TITLE
there are 2 symbols for the player position now in the minimap?

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#101]
![grafik](https://user-images.githubusercontent.com/1245084/63693501-87843380-c814-11e9-966d-7a76330f62a7.png)

- there is a red circle and the white arrow

**Comment by kb173** [comment]
The arrow is the third person view, the circle is the global player position - is that not intended?

**Comment by chrisgraf** [comment]
this is an unintended feature - I think we should keep it but improve the relation of size between the two symbols and improve the contrast/border of the symbols. Also the player position should get a direction of view like the 3rd person view
