### ISSUE TITLE
minimap symbols for pv are missing or not visible

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#102]

**Comment by kb173** [comment]
Do we have an icon for them yet?

**Comment by kb173** [comment]
Symbols were added in 4e5d50f, but since I couldn't find an icon for them in our Resources, the windmill icon is used for now.

**Comment by kb173** [comment]
Added the same icons as in the Lego project in https://github.com/boku-ilen/landscapelab/commit/f5fadf1c1a1e55d13b2c8f3a15ea32f0db3c89fa
