### ISSUE TITLE
Improve building roofs

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#107]
Pitched roofs should be much higher (and the rest of the building lower).

If possible, other roofs should be higher and more sloped as well. Ideally there is no flat area on top of smaller buildings (houses).

For large buildings, we can assume a flat roof.

http://vterrain.org/Culture/BldCity/Roof/

**Comment by kb173** [comment]
We have new roofs, but with flat roofs there is another mesh directly below the roof. This causes flickering

**Comment by kb173** [comment]
@MoritzRoth Do you have an estimate for when the remaining fixes will be done? I think the stray vertex is fixed, only removing the second inner roof is still open, right? Or will that be done after 0.4?

Asking because we should start generating the updated models soon

**Comment by MoritzRoth** [comment]
buildings improved with https://github.com/boku-ilen/landscapelab-server/commit/bc84e64de84838f0d152c71dde09ec99d9d71a51
removed inner faces with https://github.com/boku-ilen/landscapelab-server/commit/18169535e17825d0c51f11d7350c5c19a2a526fb
