### ISSUE TITLE
1.03 GB static memory used?

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#11]
According to the debugger (Monitor tab), our project is constantly using 1.03GB of 1.03GB static memory. Even in empty scenes with all singletons disabled, this persists. However, fresh Godot projects don't show this behavior and use normal, far lower amounts of static memory.

What's causing this? Is it just a display error? Presumably, we would get overflows if we were truly constantly using almost all available memory?

**Comment by chrisgraf** [comment]
is this still an issue? is it relevant?

**Comment by kb173** [comment]
Godot's monitor does still show values like this, but it seems to have no actual consequences (it's not related to #10, as previously suspected). It would be good to understand why this is the case, but since it's not a problem in any way, I assume the issue can be closed.

**Comment by chrisgraf** [comment]
let's keep it open and revisit it later

**Comment by chrisgraf** [comment]
closed as it does not affect anything
