### ISSUE TITLE
building textures flicker as if two faces overlap

### ISSUE THREAD

**Issue by MoritzRoth** [boku-ilen/landscapelab#110]

**Comment by MoritzRoth** [comment]
buildings are rendered multiple times ontop of each other
it seems that with each lod update a new building is being added

**Comment by kb173** [comment]
Seems like for some reason, buildings don't become invisible when an LOD isn't in use anymore.

Current workaround: Removing the BuildingModule in the LOD after adding it

**Comment by kb173** [comment]
The workaround has no drawbacks and buildings will be handled like dynamic assets in the future, so this won't be an issue anymore.
