### ISSUE TITLE
dynamic energy values in tooltips

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#111]
URL for requesting energy production of a single asset ^energy_contribution/(?P<asset_id>(\d+))/asset.json$

**Comment by MathiasBaumgartinger** [comment]
This should work as intended, server values are still missing however.

**Comment by chrisgraf** [comment]
the URL will change .. will be posted here

**Comment by MathiasBaumgartinger** [comment]
@chrisgraf Please tag me once the URL is updated.

**Comment by chrisgraf** [comment]
@MathiasBaumgartinger : take a look at the current push .. I think the URLs should not change anymore

**Comment by kb173** [comment]
The request needed for the tooltip is currently not working due to #136

**Comment by kb173** [comment]
The last problem with this was fixed in 91a2caa
