### ISSUE TITLE
Energy details and dropdown: Update when asset is removed and add periodical update

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#114]
When an asset gets removed the current values are not updated. This can easily be implemented by emitting signal ``"asset_removed"`` so the UI gets an update. This signal is connected with an update function.

Also update the UI perodically so assets not shown in the game engine will also be added after a short delay.

**Comment by kb173** [comment]
A custom node could be written for periodic updates, since that will be required in multiple places.

**Comment by kb173** [comment]
Since we have a very high amount of assets on the testserver at the moment, `_request_energy_value` is being spammed a lot when first instancing them. I think it should at least be given a lower priority so it doesn't block other requests.

Same with the `asset_spawned` signal, but that's being replaced with periodic updates anyways, so probably no need to fix that.

**Comment by kb173** [comment]
Custom node was added in https://github.com/boku-ilen/landscapelab/commit/42bf40a9d78006668ea4f6491dc6dfcecf48ad32 since I needed it elsewhere, if it doesn't have all required functionality it can be extended further

**Comment by MathiasBaumgartinger** [comment]
Added periodical update to the sum, in the dropdown it is a little more complicated. Changes will follow soon however.

**Comment by MathiasBaumgartinger** [comment]
Added the periodic update to both UI-elements. There might be a problem with an URL however. I suppose the ```# Request energy contribution of all assets
    url(r'^contribution/(?P<scenario_id>(\d+))/all.json$',
views.get_energy_contribution, name='get_energy_contribution_global'),```-request has a bug, as ``141.244.151.130/landscapelab-dev/energy/contribution/10/all.json`` does not show a valid response.

**Comment by MathiasBaumgartinger** [comment]
Fixed with commit #af5b72e and #083f9c7.
