### ISSUE TITLE
Display Lego map extent in Godot

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#118]

**Comment by chrisgraf** [comment]
this would require a direct connection between the client and the qgis-plugin

**Comment by kb173** [comment]
Couldn't the extent be sent to the server? Would require a new model and request, but I think it's probably easier than building that new connection somehow.

**Comment by chrisgraf** [comment]
i think this is not a good design because it would require the server to have sessions which we currently don't support

**Comment by chrisgraf** [comment]
also it is combinable with #120

**Comment by kb173** [comment]
Should #120 really be implemented using a completely different design? It seems almost the same as normal asset functionality (e.g. buildings, which only have one position as well), only with the player instead of e.g. a building.

For this, I agree that it would be more elegant, but I don't know how we could facilitate a direct connection...

**Comment by chrisgraf** [comment]
to model the player position as an asset position is an ugly approach in my point of view .. its semantically wrong

**Comment by kb173** [comment]
I'd view it more as a "PlayerPositionSuggestion" asset or something like that. The client should still have full control over where the player really is, but if the situation is right, it can teleport the player to the latest suggestion.

I think that way, it makes sense as an asset (I agree the term 'asset' isn't perfect, but technically, it makes sense), and doesn't require many changes.

**Comment by chrisgraf** [comment]
That the client is in control over the player location is a sure thing and would also be true for a direct communication between qgis/lego and the client

it's not (only) about the term but the same storage, the same routines for two logically completely different datasets

**Comment by chrisgraf** [comment]
decision: player position, teleport request and extent (upper left, lower right points) are modeled as assettypes/assets

**Comment by kb173** [comment]
Looks like this with c433024:

![image](https://user-images.githubusercontent.com/18697097/64737527-6d717300-d4ed-11e9-9b0d-a2b4f0c332c0.png)

Doesn't use the server requests yet though - only the visualization is done (both 3D and minimap)

We can change things like the opacity depending on how prominent we want it to be.

**Comment by kb173** [comment]
With 446849f the extent is fetched from the server.

We'll need to test whether we treat the coordinates the same way as the Lego board once it's implemented there, but based on test data it seems like it should work.

**Comment by kb173** [comment]
Now tested and completely functional
