### ISSUE TITLE
Add separate energy requirement values for each asset type

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#121]
* Each asset type gets an energy requirement field
* This requirement is returned in the `energy_contribution/[asset_type_id].json` request
* The total energy requirement comes from the sum of these asset type requirements instead of the scenario
* The client displays that in addition to the current energy contribution

**Comment by MathiasBaumgartinger** [comment]
With commit 5871366 the dropdown is updated. Server sided values are still missing however.

**Comment by kb173** [comment]
Remaining problems with this are in #114
