### ISSUE TITLE
do not actually delete assetpositions but handle them by change history or deletestamps

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#125]

**Comment by chrisgraf** [comment]
i currently consider all mutable assets as game objects which should be handled by the game logic part we want to introduce

**Comment by kb173** [comment]
How can we approach this now with geodata layers? Should we add "created_at" and "deleted_at" attributes to object layers? Should we allow both "soft-deleting" like this and actually removing objects from the data (e.g. for performance reasons)?

**Comment by kb173** [comment]
> we could create a copy of the "asset" layer called xxxx_history and add these modified timestamps (and maybe additional metadata later)

Good idea, this is actually close to how we currently do it with our temporary RAM dataset that holds changes - we could just save that as a new layer.

**Comment by kb173** [comment]
> > we could create a copy of the "asset" layer called xxxx_history and add these modified timestamps (and maybe additional metadata later)
> 
> Good idea, this is actually close to how we currently do it with our temporary RAM dataset that holds changes - we could just save that as a new layer.

This was implemented as described here with the GameSystem's save functionality
