### ISSUE TITLE
Streets are spamming errors

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#127]
Our streets keep throwing this error:
```Signal 'tree_exited' is already connected to given method '_path_exited' in that object.```

This seems to be a Godot issue (godotengine 30229). I asked there whether there is some workaround for this.

**Comment by kb173** [comment]
I think a possible workaround would be to remove_child and add_child the street while making changes.

**Comment by kb173** [comment]
The Godot pull request 37714 seems to fix this - it's scheduled for 4.0.

**Comment by chrisgraf** [comment]
@kb173 is this still an issue currently?

**Comment by kb173** [comment]
Yes, the errors still happen (though this has no real implications other than error spam). There's an open pull request for this that might get cherry-picked for a 3.2.x release: godot/pull/37714

**Comment by MathiasBaumgartinger** [comment]
By the way, this problem will persist with the new Layer-Structure as well and additionally in the Profile-Editor.

**Comment by kb173** [comment]
Fixed in Godot
