### ISSUE TITLE
Generalize thread priority calculation in WorldTile

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#128]
Especially with WorldTile requests, the priorities seem to be a bit off, the priority of nearby tiles is especially too low. (They are still calculated with a calculation which was intended only for testing)

Since we have multiple regular requests, we definitely want those at a different priority (which has many thread workers) than the tile loading.

**Comment by kb173** [comment]
Done in 1679743 - good enough for now, but should be generalized later.

**Comment by chrisgraf** [comment]
is this still relevant, @kb173 ?

**Comment by kb173** [comment]
no
