### ISSUE TITLE
buildings_regionen shapefile is missing the height fields

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#129]
In the buildings_K shapefiles we had `_mean` and other fields for the building heights. The new buildings_regionen does not have any of those fields.

I believe they were calculated from the DHM-DOM-difference.

Note: We need them in EPSG:3857 coordinates!

**Comment by hrralph** [comment]
Heights are calculated in a new shapefile (buildings_regionen_heights_epsg3857.shp)

**Comment by kb173** [comment]
Thanks @hrralph! I had a look at the data too, looks good :+1:
