### ISSUE TITLE
the client should start in a maximized window

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#13]

**Comment by chrisgraf** [comment]
this is somewhat implemented now .. the splash screen on windows still starts in the resolution of the splash image

**Comment by kb173** [comment]
> the splash screen on windows still starts in the resolution of the splash image

I believe activating 'Fullscreen' (and maybe 'Borderless') in the project settings at Display -> Window applies it for the whole project (even before AutoLoads are loaded), so this would include the splash image. However, this also gets rid of the window title bar. Do we want this?
