### ISSUE TITLE
processing new dhm data

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#133]
current status:
- data from my local disk are transfered to ilen-q (resources folder)
- K data is missing the coordinate swapping
- copying AT + K data together is still missing

**Comment by kb173** [comment]
I added a command for removing partially transparent (incomplete) tiles in the server, it is currently being applied to the K data. Once that is done I will copy+replace the K data into the AT data.

**Comment by kb173** [comment]
The data is finished and now being uploaded! Leaving the issue open until it's done and has been tested

**Comment by kb173** [comment]
The data is done uploading and now under `resources/raster/dhm` in the ilen-q, so it's automatically used when using the mounted resources. I've tested it in all scenarios and it looks good!
