### ISSUE TITLE
Streets can crash the game after teleporting

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#134]
When teleporting, it can happen that the game crashes with a posix socket error. This only happens when the LinearAssetHandler for streets is active. I assume this is related to how streets handle the GroundedSpatial's grounding function.

**Comment by kb173** [comment]
I could narrow this down to the `_vectorize_points()` function in the LinearAssetHandler. Seems like it's not related to the GroundedSpatial like I originally thought.

**Comment by kb173** [comment]
It's the `_interpolate_points()` call that causes this. This is strange - the crash didn't happen previously, and I don't think anything changed there... It's really the function itself, not something else that's the result of it, since even calling it and not doing anything with the result breaks things.

The function is recursive, so that might be why it's just spitting out a C++ error.

Interpolating the points is only necessary in some situations, in fact I didn't directly notice any difference without it. Workaround added in 89e0332 (commented out the function call).

Changing to bug and needs testing - the function may not be necessary at all.

**Comment by chrisgraf** [comment]
is this a godot issue?

**Comment by kb173** [comment]
Could be, I really don't know what exactly in the `_interpolate_points()` call could cause it - especially since it doesn't happen when first loading, but only after teleporting. I guess the only options are either the recursion or the `Array.insert()`.

It also has never happened on my Linux machine, so yes, an issue in one of the OS-specific drivers of Godot is possible. We'd need to do more testing though...

**Comment by kb173** [comment]
It turns out that `_interpolate_points` can really recurse too deep in some rare cases, causing this crash. The parameters have been tweaked, so this is fine for now. In the future, we should make this function more efficient.

**Comment by kb173** [comment]
The function doesn't recurse anymore, so this should be fixed.
