### ISSUE TITLE
Monitor and save statistics about what's happening, loading, etc. in the LandscapeLab

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#135]
Since we currently have a huge (and unrealistic) number of assets on the server, Godot can hang for seconds when all are loaded and a tile updates. This is because the new GroundedSpatial gets the new height when a tile changes, and we have thousands of individual PV modules currently.

So many assets are simply something that shouldn't happen in a real scenario, so I think we should display a warning message in that case (so if it does happen for some reason, like now during testing, we know what's wrong).

**Comment by kb173** [comment]
There is a limit to how many assets are loaded, but it may still make sense to display the number of assets somewhere. Maybe in the debug window.

**Comment by chrisgraf** [comment]
i generally think that we need some more statistics in the landscapelab itself about what is going on, what is loaded etc.

**Comment by kb173** [comment]
https://github.com/boku-ilen/landscapelab/commit/77327f4e7b240f7996b1376751b36ef67606b5ab added a basic "Loading" text for when the LayerRenderers are currently fetching new data. For more detailed statistics, it might make sense to let each individual renderer keep track of some relevant metrics.
