### ISSUE TITLE
Document main program aspects, UserInterface and usage for LandscapeLab, LegoLab and QGis-Plugin

### ISSUE THREAD

**Issue by MoritzRoth** [boku-ilen/landscapelab#144]
Also
- start commands
- relevant config 
- settings
- button mappings
- known issues + workarounds

**Comment by luxkon** [comment]
I started the documentation but its just a first version. There are still descriptions missing and I ask everyone to simply add missing parts. I also will continue on that. 
https://docs.google.com/document/d/1nA8A2Mg6OdrGxOdaQHiCFaPGZHNhLfKei3oMakZk8H0/edit?usp=sharing

**Comment by kb173** [comment]
The documentation is looking good. If we notice something missing during the first workshop, we can add it for the later ones where we have fever developers present. Leaving it open until then

**Comment by MathiasBaumgartinger** [comment]
As the workshops go to an end, this issue does aswell. :+1:
