### ISSUE TITLE
PoIs: Custom addable Points of Interst

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#155]
Make a button to add custom Points of Intersts. For example at current location.

**Comment by MathiasBaumgartinger** [comment]
Implemented in the client and with commit https://github.com/boku-ilen/landscapelab-server/commit/4663d4ada0823ed754657ab4c9098afb97df77c4 also functionality for the server.

Also the option to increase or decrease the order of a PoI is implemented in the server, have to apply the requests in the client however.

**Comment by chrisgraf** [comment]
we have to move this functionality away from the server. The POIs will come in the (readonly) geopackage. Maybe managing POIs can be an exception of the readonly constraint. this has to be discussed

**Comment by kb173** [comment]
part of #245
