### ISSUE TITLE
Add framework for VR toolbox

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#158]
In VR, different tools should be able to be bound to the controller. Once a tool is selected, the controller's behavior and buttons change to that tool.

We want to write a framework for Nodes which can be added as a child of the ARVRController (or extend it?) to make this easily expandable.

For example: The player selects distance measurement (measuring tape) tool (by grabbing it?). Now, when pressing the trigger, a tape can be drawn, and the distance is shown.

The right controller will always be a certain tool; the left controller handles base functionality (e.g. opening the toolbox)

**Comment by MathiasBaumgartinger** [comment]
Added a GuiToMesh-node today with 554a7f24d6ad9463be3ef548afdd818ac6b7b300

**Comment by MathiasBaumgartinger** [comment]
Transfering this to the new VR-toolkit repository:

https://github.com/boku-ilen/godot-vr-toolkit/issues/1
https://github.com/boku-ilen/godot-vr-toolkit/issues/2
