### ISSUE TITLE
Generalize and improve UI

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#159]
The UI is specific to the Retour energy project at the moment. We want to generalize and improve it so it's easily usable and expandable in any project.

**Comment by MathiasBaumgartinger** [comment]
We should probably further discuss on how to approach this topic. I don't want to make any conclusions on my own, as this could be critical.

In my opinion we should put a big focus on making a "lite" version of the UI. In it's current state its not really well-structured.

**Comment by MathiasBaumgartinger** [comment]
Translation concept is now added, in the future it is recommended that:

If you want to make a new UI-text, use the global ``tr("STRING_ID")`` method. First you have to make sure to add the ID and the translations into the translation ``.csv``-File. The language can be changed in the newly designed settings. If you want to change it from code use the global ``TranslationServer``.

**Comment by MathiasBaumgartinger** [comment]
With 8dfb01e88e23f5db4fd56348d832725e9d803735 and cf0e82e247caab0f8957a7a13836792d9b544885 we now have a hoverable tools bar.

**Comment by MathiasBaumgartinger** [comment]
Commits a696adaae6aad857c4033524d34bbffdd0ddf5f8 and 83c8fedc2aa89e9462092d37e9fd41a67e5daa85 as well as 1fc16ec7174c1cb11334da23f3ead1af4b496b0b the first steps towards a new and generalized ui have been made.

Values can now be configured in a settings file, values will have a field ``modes`` -> an array of integers (careful json does not specify ``integer`` and ``float`` only number, godot takes every number as ``float``) and will be loaded according to the current mode.

Similar behaviour will be implemented for the tools.

**Comment by MathiasBaumgartinger** [comment]
Commit d05904c80ea07539d3817c864b46a4eb3a098978 kind of finished the tool-bar.

**Comment by MathiasBaumgartinger** [comment]
This has been moved to #197
