### ISSUE TITLE
Connect the client to QGIS to exchange data in real-time

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#162]
To make it easier for non-developers to load new data or specify what data should be used, we should get rid of the manual preprocessing workflow and instead connect QGIS to the client, so that the client fetches all data from there.

This will likely also change how we handle images (tiles).

edit: Changed 'server' to 'client' since we could use this opportunity to get rid of some programming and performance overhead and omit the server.

**Comment by chrisgraf** [comment]
i am planning a direct connection to our qgis-plugin for exchanging something like the current position etc. We could also extend this functionality in the future to enable layer-management/visibility etc by qgis but this would bind qgis closer to the landscapelab and I am not sure if this is the best way to go. As we proposed now the posibility to dynamically load additional geodata maybe this management should be done directly in the client?

**Comment by kb173** [comment]
This is not relevant for data loading (this happens via the GeoPackage anyways), but for exchanging e.g. the player position. This could probably use the same WebSocket (?) implementation as the Lego table.

**Comment by MathiasBaumgartinger** [comment]
This issue came somewhat out of fashion, since the whole loading process works very different from then (i.e. gpkg instead of server, etc.)

@chrisgraf we are currently cleaning up the issue backlog. Is this still relevant to you? If so, can you elaborate on how you would image this today?

**Comment by kb173** [comment]
decided that this is sadly out of scope
