### ISSUE TITLE
Add global clay rendering switch

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#172]
We want to be able to swap out the existing vegetation shader with a clay rendering shader. Different approaches might work for this.

A first start might be to render the existing vegetation in all white (possibly with a small derivation based on the mean color in the original image). The edges should be smoothed out to create a more clay-ish look.

A different approach would be to use different meshes entirely for this clay renderer. e.g. small sticks for the herbage module, large cylinders and spheres (simple trees) for the larger tree modules, ...

**Comment by kb173** [comment]
![image](https://user-images.githubusercontent.com/18697097/74353818-bf7b3500-4dba-11ea-87f1-7c5e032f0367.png)

Setting everything to white already has a nice effect. We need to visualize slopes much better though. Perhaps the normals can be exagerrated. We should research what is usually done for solving that.

**Comment by kb173** [comment]
The improved terrain normals are sufficiently good at visualizing slopes imo.

Also, while testing land-use data, I noticed that directly visualizing the land-use IDs has a very nice effect. We could even use a 1-dimensional texture to color-code the different IDs. This might be good for a basic abstract view!

![Screenshot_2020-03-05_17-55-24](https://user-images.githubusercontent.com/18697097/76004903-8beb8080-5f0a-11ea-853c-bdbb419fb10d.png)

**Comment by kb173** [comment]
As mentioned in #211:

> Comparing against the name of the new style feels a bit ugly though, and it introduces some programming overhead for anything that's rendered (since it has to react to style changes and implement every style).
> I'd prefer a purely render layer solution, where the RenderStyle singleton simply switches render layers on and off depending on the new style. However, it would be a big waste of resources to have multiple meshes active for things like the terrain.
> We should do some more thinking and testing before settling on a solution for this.

Ideas / progress will be kept track of here.

**Comment by kb173** [comment]
I've noticed that many implementations will have a shader with a variable `clay_rendering` that's either true or false, depending on the RenderStyle. We could add VisualInstances with a shader with such a variable to a group which is automatically updated centrally - that way, there is no additional programming overhead for them.

**Comment by kb173** [comment]
Once thing that's tricky with signals is setting the initial parameter. Reacting to signals is fine, but every time a VisualInstance with a clay_rendering flag is instanced, the flag must be set to the current value. I don't think there's a way to add something to the `_ready` function for all nodes of a group...

**Comment by kb173** [comment]
I asked for ideas here: https://godotengine.org/qa/64662/how-to-do-something-when-node-in-a-certain-group-is-instanced

**Comment by kb173** [comment]
A temporary solution was added in https://github.com/boku-ilen/landscapelab/commit/bdab78d5b63c1e036054afbb06bb8907b112d24d. We might want to open a feature request for this in Godot, since being able to use groups as traits would be beneficial in many situations.

**Comment by chrisgraf** [comment]
please open a request for this if you think it is beneficial for more..

**Comment by kb173** [comment]
I opened the request in the godot-proposals repo ("Custom function to call when a node with a certain group is added #627")

**Comment by kb173** [comment]
We will be able to do this very neatly in Godot 4.0 with this feature which was just announced: https://godotengine.org/article/godot-40-gets-global-and-instance-shader-uniforms

With this, we can just set a global shader variable and we're done, no need to access any specific objects!

**Comment by kb173** [comment]
Basic clay rendering for terrain is available with the BasicTerrainLayer.

White vegetation is also doable in theory, but probably not necessary in the near future, so closing this until there's a more specific use-case
