### ISSUE TITLE
Raster data can very rarely be unavailable due to 'Permission Denied'

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#178]
Very rarely, we have broken (high and white) tiles because the server fails to create the corresponding image. This is accompanied by a "Permission Denied" error while calling "Image.open" in `tiles.py` in the server (from PIL).

As far as our testing showed, this only happens on the Workshop PC on Windows, meaning it is either caused by Windows or by the hard drive of that PC.

**Comment by kb173** [comment]
If we do #177 as proposed, the code causing this issue would be obsolete.

**Comment by chrisgraf** [comment]
as #177 is done with the introduction of geodot this now becomes obsolete
