### ISSUE TITLE
Differentiate between drag and click

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#179]
For diverse tools it will be required that we distinguish between a mouse-drag (mouse_down and dragging) and click (mouse_up and not dragging). 
This for example happened with the Imaging-tool while setting paths for example.

**Comment by kb173** [comment]
Should be considered in the process of  https://github.com/boku-ilen/landscapelab/issues/243

**Comment by MathiasBaumgartinger** [comment]
@kb173 I think you unified the movement. Any further information here?
