### ISSUE TITLE
Add way to draw assets from the server with the method we use for the Dolly path

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#181]
Mainly for power lines, and also fences etc

**Comment by kb173** [comment]
Unify this with the current road system

**Comment by chrisgraf** [comment]
@kb173 is this still relevant after the introduction of geodot?

**Comment by kb173** [comment]
No, I'd say this can be closed. We have the ability to construct Paths from vectors in shapefiles, so that can be used for anything like power lines and fences. It's also used for the roads.
