### ISSUE TITLE
Improve UI handling and elements

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#19]
The minimap and other UI-Elements (Walkmode, VR, Debugmode, Placement-Slider, ..) are not shown in client by default

**Comment by chrisgraf** [comment]
most of the items are now included - still some wiring has to be done --> WIP

**Comment by chrisgraf** [comment]
future plans:
- move ui elements only available for the minimap into the lower left corner of the minimap
- also make a change button for minimap between map and ortho
- add more debug buttons and displays

**Comment by kb173** [comment]
Since bigger changes will be done in the UI now to get away from Retour-specific functionality, this is now tracked in newer issues like #159.
