### ISSUE TITLE
Sometimes the game crashes, no apparent reason found yet

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#190]
We will try to keep track of this problem. If you should notice any irregularities please contact this issue!

**Comment by MathiasBaumgartinger** [comment]
Nockberge testregion on startup

commit fe8ba6b799280120482acffe2bb686711122472a

**Comment by kb173** [comment]
Seems to be related to something we changed today - barbara got multiple crashes while recording, that never happened in the previous days.

From my commits, I would say 1cf58e352707db2b568e10a1e1186ac8ce976712 is the most likely candidate - will investigate.

@MathiasBaumgartinger can you check your commits too?

**Comment by kb173** [comment]
I got a crash and a pause now while testing (local laptop), both times the debugger stopped at the line:

```clamped.x = clamp(player_pos.x, origin.x, end.x)```

(Line 322 in WorldTile.gd)

According to the debugger though, all variables were valid. Maybe some other thread had an issue at the moment where the main thread was working on that line, but it's curious that it was the same line twice...

**Comment by kb173** [comment]
The changes made in https://github.com/boku-ilen/landscapelab/commit/1cf58e352707db2b568e10a1e1186ac8ce976712 got obsolete with the Geodot rewrite on the Geodot branch and I haven't experienced any crashes there. Seems like that was the reason (or something else in the tile loading). 

Needs testing on the Geodot branch.

**Comment by chrisgraf** [comment]
@kb173, @MathiasBaumgartinger : can we resolve this?

**Comment by kb173** [comment]
Yes, let's open new issues for future crashes. This specific one is likely resolved with Geodot.
