### ISSUE TITLE
Possible Tools (GIS, etc.)

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#191]
To have a place for all the good tool ideas i created an issue. Comments with any ideas are very welcome. =)

**Comment by kb173** [comment]
Seeing and being able to enter an exact position (in WGS84 coordinates) would be very helpful, + additional information such as view direction. Maybe it could be integrated into the teleport tool.

**Comment by MathiasBaumgartinger** [comment]
A flexible "Layer"-tool to change, enable/disable, etc. different types of layers.
This could be helpful on our "asset-mask"-tool #189, aswell as discussed heat-map textures for e.g. houses (temperature values / insulation), or streets (traffic values) and so on.

**Comment by MathiasBaumgartinger** [comment]
A compass symbol for 3D-view aswell.

Related to #149

**Comment by MathiasBaumgartinger** [comment]
Re-add teleportation to VR #164

**Comment by MathiasBaumgartinger** [comment]
**Add a minimap card as tool for VR.** -> Render minimap camera onto a mesh.

**Comment by MathiasBaumgartinger** [comment]
Re add compass for non VR #149
