### ISSUE TITLE
Player position changes slightly when changing views (with First Person view)

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#192]
Happens both when first instancing the first person view, and when switching perspectives

**Comment by chrisgraf** [comment]
do we know a reason for this behaviour?

**Comment by kb173** [comment]
Yes, this will most likely be resolved as part of #219, but I suggest leaving it open until then so we test it again once that's done.

**Comment by kb173** [comment]
#243  makes this redundant
