### ISSUE TITLE
Investigate performance bottlenecks

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#194]
We should look through critical code and try to optimize it. Especially tile code, which is called very often every frame. Shaders too. I believe that with some optimization, we could display a lot more detail with better framerates, and also decrease loading time.

One thing I have noticed is that generating the heightmap colliders takes a long time. 1cf58e352707db2b568e10a1e1186ac8ce976712 attempted to solve this and caused a noticeable improvement in loading time. However, its thread safety should be investigated (#190?)

**Comment by kb173** [comment]
I asked a question in the Godot QA forum regarding shader performance: https://godotengine.org/qa/62279/how-far-should-re-using-shaders-be-taken

**Comment by kb173** [comment]
It seems like procedurally getting the normals in the terrain shader is pretty costly due to the many texture reads. Godot offers a function to do it once on the CPU: https://docs.godotengine.org/en/3.1/classes/class_image.html#class-image-method-bumpmap-to-normalmap

We could do that in a thread and pass it as an additional parameter. That way it isn't done every frame.

**Comment by kb173** [comment]
I tested this and there is a noticeable performance increase. However, the normals acquired with this method aren't as good as the ones we calculated in the shader. Thus, a new issue for this was created here: https://github.com/boku-ilen/geodot-plugin/issues/14

**Comment by chrisgraf** [comment]
@kb173 : this is a quite general issue .. are there some more known cases where we can improve performance? maybe we should split this into separate issues? The general task of thinking about bottlenecks/performance is probably not an issue?

**Comment by kb173** [comment]
Yeah, this was mainly about a more detailed investigation which lead to some of the rewrites which are done now (normal map, vegetation, ...). We can close this and open more specific issues if we notice that there's a system that could have bottlenecks.
