### ISSUE TITLE
The UI does not properly scale for different resolutions right now

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#197]
Some investigations have showed, that in the project settings under ``display -> window -> stretch`` the display of the UI can be altered. However with Mode = 2d and Aspect = expand we have some pixel aliasing problems.

Further investigate this.

**Comment by MathiasBaumgartinger** [comment]
3716ac7 changed this behaviour a bit. Instead of applying any settings i added another margin-container which in my experience is independent of resolutions. Have to do some fixing with the UI now however.

Please more testing and feedback.

**Comment by chrisgraf** [comment]
my impression on 4K was that the UI is a bit small

**Comment by kb173** [comment]
We haven't encountered any issues with this anymore
