### ISSUE TITLE
Generalize geodata definition (add attribute names) within GeoPackage and document format

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#214]
Currently the geodata files are specified in geodata.json, but attribute names (such as the width of streets) is hardcoded. We want to add these names to the config file. Also, the expected format of entries in that file should be documented (e.g. heightmap -> Float32, infrastructure -> LineStrings or MultiLineStrings). Maybe we could do this directly in the geodata file with a "description" field?

**Comment by chrisgraf** [comment]
We probably will ship the geodata in geopackages which also provides the possiblity to add configuration tables

**Comment by MathiasBaumgartinger** [comment]
@kb173 @chrisgraf this is a redundant issue with the introduction of the geopackage, right?

**Comment by chrisgraf** [comment]
this is initially done by 5edef38 - to be further refined

**Comment by MathiasBaumgartinger** [comment]
Currently, the ``LayerConfigurator.gd`` hardcodedly extracts data from the geopackage or other sources. This introduces a lot of additional work and makes versioning very hard (different versions of GPKGs and LayerConfigurators floating around everyhwere). Instead, the LayerConfigurator should digest a **Configuration** in form of a table from the geopackage.

As can be seen in https://github.com/boku-ilen/landscapelab-geodaten/compare/c799618e9229...76dbc33c72a2, we agreed on the following tables:
- ``LL_layer_configuration``: A table for the LL layer that should be produced, that states it's render type and some additional information
- ``LL_layer_configuration_extension``: A table for additional information on primitive types (with a reference name to the to be configured layer (e.g. "my_terrain") and key -> value ("extent" -> "1.5")
     - We might create additional tables for each data-type here. For now just parse them.
- ``LL_geolayer_to_layer``: A table that connects a geo-layer to a LL-layer, including the name of the to be configured layer (e.g. "my_terrain")
- ``LL_geo_layer_type``: A table that stores the possible geo-layer types as defined in the render-infos in ``Layers/Layer.gd`` (e.g. "height_layer", "texture_layer")
- ``LL_render_types``: A table that stores all possible layer render types ("basic_terrain", "object", ...)
- ``LL_configuration``: A table for general LL info (start point, etc.)

**Comment by MathiasBaumgartinger** [comment]
https://github.com/boku-ilen/landscapelab/pull/269
