### ISSUE TITLE
Dynamically load assets from point data with pre-defined meshes

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#215]
Once https://github.com/boku-ilen/geodot-plugin/issues/21 is done, we can easily retrieve point data from e.g. a shapefile. We want to be able to load assets (meshes) based on such point data. Which specific mesh is used often depends on an attribute of the point.

**Comment by kb173** [comment]
In https://github.com/boku-ilen/landscapelab/commit/da9e3cc0143ae7e8c88bee6a2b04e620ff1706fe, a node was added which can load different assets based on the value of an attribute in GeoPoints from a Shapefile.

This was implemented for power poles:

![image](https://user-images.githubusercontent.com/18697097/79239114-76a23400-7e70-11ea-97f6-ebfdc74280fb.png)

The same can be done for other shapefiles pretty easily - you just need to set an attribute and map its possible values to PackedScenes.

It would theoretically be nice to expose this even further, to something like a config json. However, we have to implement the Asset in the editor anyways (to allow additional functionality and because of the challenge of importing meshes at runtime), so I'm not sure if that's feasible...

**Comment by kb173** [comment]
This is on hold since it will be largely solved by the layer rewrite. Keeping the issue open to ensure that this functionality will be fully included.

**Comment by MathiasBaumgartinger** [comment]
Related to #236 and #230

**Comment by kb173** [comment]
The implementation of this as an ObjectLayer needs to be finished.

**Comment by kb173** [comment]
The ObjectLayer functionality for rendering objects is now finished. Leaving this open until the UI is adapted as well.

**Comment by MathiasBaumgartinger** [comment]
Since i don't really find any example/documentation on how to use it, I am going to request a bit of help here @kb173.

I will clasically obtain metadata via ``get_selected_metadata()`` then will create a ``FeatureLayer`` representing the points, right?

**Comment by kb173** [comment]
For future reference I'll just post the example here as well:

```gdscript
    # Test Point Data
    var windmill_layer = FeatureLayer.new()
    var windmill_dataset = Geodot.get_dataset("/home/karl/Downloads/ooe_point_test.shp")
    windmill_layer.geo_feature_layer = windmill_dataset.get_feature_layer("ooe_point_test")
    windmill_layer.render_type = Layer.RenderType.OBJECT
    windmill_layer.render_info = Layer.ObjectRenderInfo.new()
    windmill_layer.render_info.object = preload("res://Objects/WindTurbine/GenericWindTurbine.tscn")
    windmill_layer.render_info.ground_height_layer = height_layer.clone()
    windmill_layer.name = "Windmills"
```

**Comment by MathiasBaumgartinger** [comment]
Functionality for this is here - marking it as needs-testing.

**Comment by kb173** [comment]
This has been tested for a while now, and it was even extended to work with dynamically loaded OBJ meshes in https://github.com/boku-ilen/landscapelab/commit/681d5f46efed126c738ef27b342b92a6054852f6. Both methods seem stable and the result looks as expected.
