### ISSUE TITLE
Rewrite vegetation with Geodot and more efficient rendering system

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#217]
A major limitation of the current vegetation system is the large amount of renderers that are required: At high LODs, there are up to 15 renderers per tile (5 layers, 3 phytocoenosis per layer). The amount of tiles (and thus renderers) required rises with how finely we want to control where a lot of vegetation is drawn. Because we want to render a lot of grass very close to the player, this contradiction results in a performance bottleneck.

In addition, since all data is loaded from the server, loading the vegetation modules takes significantly longer than the terrain modules which have been adapted to Geodot.

I propose a new system:

- Renderers are per-layer, not per-tile -> We can optimize the amount of renderers
- The position of renderers relates directly to the camera position -> We can draw dense grass directly around the camera and nowhere else
- Vegetation data is loaded with Godot/Geodot, without the server -> Much faster loading speed

**Comment by kb173** [comment]
Some basics for this were implemented in https://github.com/boku-ilen/landscapelab/commit/272ee0da1c03af6f240a45aebf6e620c800c8f63: Vegetation spritesheets per phytocoenosis are created on-the-fly directly in Godot. We now need code which combines these spritesheets into the finished spritesheet for the shader, which dynamically include all relevant phytocoenosis.

**Comment by kb173** [comment]
This is mostly done:

![screenshot](https://user-images.githubusercontent.com/18697097/80728063-cc303f00-8b06-11ea-806a-4f4eeb617968.png)

Some things remain to do:

- As a performance optimization, we might want to use a grid of 4 or 9 particle systems instead of just one. This allows Godot to do culling, thus ideally only rendering ~half of the particles (since most are behind the player).
- The height of the plants is not correctly applied yet. We need to be able to apply a scale to the images which are put into a spritesheet by SpritesheetHelper.
- Tweak the number of layers, their heights, etc.

**Comment by kb173** [comment]
Another thing that might be worth looking into: Fading the plants out at a distance to prevent the abrupt change of full vegetation to no vegetation. Full float opacity should be avoided (makes things weird with alpha sorting), so a checkerboard pattern of transparency (discard some pixels, don't discard some) is probably viable.

**Comment by kb173** [comment]
This checkerboard pattern transparency is described here: https://digitalrune.github.io/DigitalRune-Documentation/html/fa431d48-b457-4c70-a590-d44b0840ab1e.htm

**Comment by kb173** [comment]
https://github.com/boku-ilen/landscapelab/commit/82adaa20075682f266183d97dac9ca3043256505 added scaling to the SpritesheetHelper, used by the Vegetation to scale plants appropriately.

**Comment by kb173** [comment]
The checkerboard transparency was added in f6de20f:

![image](https://user-images.githubusercontent.com/18697097/81311397-a31f2980-9085-11ea-9cfe-ff8d3f353a52.png)

**Comment by kb173** [comment]
The proposed performance optimization doesn't seem to make a difference after some testing - seems like it can be left as is.

The only thing left to do is make the height more precise: Plants can be a bit in or above the ground in steep areas. I assume this is because there is potentially a minor offset in the heightmap caused by its rough resolution. We'll want to clamp the position to the heightmap resolution.

**Comment by chrisgraf** [comment]
we also discussed to introduce a roughness/bumpmap to the ground where no more detailed real height data is available

**Comment by kb173** [comment]
The remaining points are fixed by the adaptation to the layer system.
