### ISSUE TITLE
Decouple terrain from global positions and global singletons

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#219]
For functionality like the VR table, we want the terrain to be independent of global positions and, theoretically, allow multiple terrains to exist at the same time, etc.

A first step towards this was done in https://github.com/boku-ilen/landscapelab/commit/55fce3d1b0dd7ef5b1fa98b3f3270dfaff7bed70. We need to remove all global_transform references and instead make them relative to the Terrain scene. The Offset singleton will be removed, this functionality will be in the Terrain scene.

Global ground positions need to be reconsidered as well. Instead of the WorldPosition workflow, we want to make everything more self-contained.

Instead of:

WorldPosition.get_on_ground -> TileHandler.get_on_ground -> WorldTile.get_on_ground <-> TerrainCollider.get_on_ground

We could do this:

Raycast -> TerrainCollider -> get_on_ground

**Comment by MathiasBaumgartinger** [comment]
The whole offset will no longer be functioning by using the playerposition - much rather it will be set by the game-state, or mode (our thought was to use remote-transforms). 

Further steps:

* Move setting offset away from the session, every game state should be able to handle this via a session call. 
* ``get_true_player_position`` will be (mostly) reworked into the new center_position.
* Signal for shifiting comes from terrain -> change connections.
* ItemSpanwder collision can be handled over the collider (local to world (mercator) coordinates). The collider has a tile as parent, this knows the terrain.


For other scripts/functionalities that require the offset, we have not yet found a solution.

**Comment by MathiasBaumgartinger** [comment]
I guess as this needs to restructure, well kind off everything, we should further investigate refactors: 

* The abstractplayer system seems kind of dull as of now.
* We should reconsider how the viewports are set (miniview and main view).
* PoI, Imaging and other tools are not working right now
* Lego functionality has to be redisgned as well

**Comment by MathiasBaumgartinger** [comment]
#235 will probably solve this problem, leaving this open for now however.
