### ISSUE TITLE
Rework how settings will work

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#221]
as we plan to introduce spatialite/geopackage as shipping the geodata also all configuration which is related to this data (like scenarios, game-settings, etc.) could be stored there.

we have to decide which settings are data-based and which are client-based and where to put them. We also might have to define local defaults, which can be overwritten.

**Comment by MathiasBaumgartinger** [comment]
Linked to #237

**Comment by kb173** [comment]
sufficiently described in https://github.com/boku-ilen/landscapelab/issues/237, which represents the implementation.
