### ISSUE TITLE
adding the geodata contributer & license used in the current view somehow

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#223]
my current idea is to display a symbol with the "level of licensing" eg .open data vs. proprietary and on mouse over or click a detailed overview of the data provider and license is shown

**Comment by MathiasBaumgartinger** [comment]
WIth d5d50019a2ade18622c9c8cc7844956cbd447f68 displaying a simple license with the possibility to add more detailed descriptions in a popup is possible.
