### ISSUE TITLE
include charts in the UI

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#227]
we are looking forward to include matplotlib via godot-python for this. As an alternative we could develop widgets for this on our own.

We want to provide realtime-charts, charts for results and even maybe multiple geo-located charts as info hovering above certain locations.

**Comment by kb173** [comment]
Relevant for both game logic and #224.

**Comment by kb173** [comment]
The main difficulty here is for passing the result image back to Godot.

**Comment by chrisgraf** [comment]
eg. power output over time for a solar panel

**Comment by kb173** [comment]
Wating for a specific use-case to implement this.
