### ISSUE TITLE
introduce the concept of time

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#229]
we currently only have time in the dolly-animation. but it would make sense to generally be able to show something time-dependent.

for instance:
- a replay function of what happened during a workshop in accelerated time
- showing the development of a landscape over time
- building realtime or turn-based serious games

**Comment by kb173** [comment]
This is mainly about filtering data by timestamps, right? Perhaps with interpolation between timestamps for smooth movement.

**Comment by chrisgraf** [comment]
i think it is more .. especially when we base game logic around that but as a first step for the purpose of displaying different points in time the usage of different geodata depending of the timestamp will work

**Comment by MathiasBaumgartinger** [comment]
Again stumbled across this issue: I think it is necessary to clarify what the "concept of time" means and then to subdivide into smaller portions. I think it is important to mention that currently we have two "concepts of time": 

1. The in-game time which determines the sun position and windmill warn lights
2. A session time which is a little bit more abstract. How is it determined exactly? @chrisgraf you mention it is more than than just timestamps, but how do you plan to model this? Is your wish to backtrace the planning process of one e.g. specific wind-turbine? This is hardly possibly, as the landscapelab and geodata in general can not distinguish whether people on the outside decide on where one specific windturbine shall be placed. Objects have one position or are not existent.

Furthermore, I think it would be smart to try to subdivide this task into smaller subtasks.

**Comment by chrisgraf** [comment]
There are very probably 'different times' - along those this task could be subdivided:
1. the in-game time for visualisation
2. the time of the data which is used for timelapses, comparisons, scenarios etc.
3. the game time (in game rounds) which is used by the game engine for different game rules, events, step-wise development of scenarios etc.

can you think of different/more 'times'?

**Comment by chrisgraf** [comment]
regarding the backtracking of a planning process:
- storing the history of the creation and deletion of the different assets along the timestamp when this happend should be enough
- maybe with a more advanced object tracking mechanism it is possible in the future to update an asset

**Comment by MathiasBaumgartinger** [comment]
> There are very probably 'different times' - along those this task could be subdivided:
> 
>     1. the time for visualisation
> 
>     2. the time of the data which is used for timelapses, comparisons, scenarios etc.
> 
>     3. the game time (in game rounds) which is used by the game engine for different game rules, events, step-wise development of scenarios etc.
> 
> 
> can you think of different/more 'times'?

1. The time of visualization is there (e.g. sunposition, windturbine blinking, etc.)
2. For time of the data, we will add a new issue (at #297)
3. The game time in rounds is implemented via the GameSystem




> regarding the backtracking of a planning process:
> 
>     * storing the history of the creation and deletion of the different assets along the timestamp when this happend should be enough
> 
>     * maybe with a more advanced object tracking mechanism it is possible in the future to update an asset

Via saving at different times using the saving functionality, different planning steps can be
