### ISSUE TITLE
asset placement is not below mouse pointer

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#23]
the assets currently are being placed directly in the direction the player looks but should be placed directly below the current mouse pointer location. This is also true if the mouse is over another viewport: then the location should be taken from this other viewport

**Comment by kb173** [comment]
With 802eea5, the mouse location is used in first person view as well. However, handling different viewports still needs to be done.

**Comment by kb173** [comment]
Closing since #48 describes more narrowly what remains to be done.

**Comment by chrisgraf** [comment]
no, #48 is something different

**Comment by kb173** [comment]
What's left to do here, other than what's described in #48?

**Comment by chrisgraf** [comment]
#48 is releated to mouse controls .. this is releated to the placement of assets (wind turbines, etc) which should be below the mouse pointer

**Comment by kb173** [comment]
802eea5 places them below the mouse pointer for me... is it not working for you?

**Comment by kb173** [comment]
Placing assets by middle-clicking on a spot is working, so I'm closing this issue.

There is only a small inprecision which is now described in #76.
