### ISSUE TITLE
simplify deployment by using a known geopackage

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#230]
the default geopackage which is looked for should be called landscapelab-data.gpkgx and be located on the same level as the packaged godot executable.

the loaded geopackage should be selected by an optional runtime parameter

**Comment by chrisgraf** [comment]
this also gets rid of the settings.ini file

**Comment by MathiasBaumgartinger** [comment]
For the use of the geopackage we have defined:

* An API for accessing Geodot inside the LandscapeLab
* A ``Configuration``-node which will contain all information about the configuration of the LandscapeLab (Layer-Structure, LoD, Offset, Tools, UI, ...)
* A distributor for geodata from which all geodata can be obtained

**Comment by kb173** [comment]
The newer, more detailed issues cover this well enough.
