### ISSUE TITLE
intruduce random roughness/bumpmap 

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#232]
even if we get a more detailed heightmap depending on the ground properties/land use we might have to provide artificially added intermediate height points with a random offset to create the illusion of more detail.

**Comment by chrisgraf** [comment]
@kb173 is this a duplicate of #182 ?

**Comment by kb173** [comment]
Yes I'd say so.

**Comment by chrisgraf** [comment]
closing as duplicate
