### ISSUE TITLE
"Merge" VRTableTop-branch into real landscapelab

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#238]
With the new encapsulated landscapelab described in  #235 it is finally time to integrate the VRTableTop branch into the master branch. A simple merge will probably not work as there are too many differences on my somewhat cheated version of the VRTable-branch.

**Comment by kb173** [comment]
out of scope for now; if we do need a VR planning mode for a future project we'll create a new detailed issue
