### ISSUE TITLE
Find workaround to display the absolute PlayerPosition as ``PlayerInfo.get_true_player_position()`` is no longer callable

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#239]
As title says with commit d8314d1 i have changed the total position in the debug panel.

**Comment by kb173** [comment]
I fixed something related to this in https://github.com/boku-ilen/landscapelab/commit/2b75c0c7821113a6e2b9d454a5875f5973b2e780 but didn't notice this issue for it. The displayed position is correct and obtained in a sensible way, so I'll close this.
