### ISSUE TITLE
asset placement in not loaded tiles crashes godot

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#24]
If I try to place an asset on a tile, which is freed it crashes with the following stacktrace:

![illegal_placement](https://user-images.githubusercontent.com/1245084/57245664-a8ddcb80-703b-11e9-82e5-d60d27c62e69.png)

we have to check somewhere if the tile is still existing

**Comment by kb173** [comment]
As mentioned in #22, this is something that should never happen unless there are other bugs which somehow cause a tile to crash or not delete itself properly, so this should be fixed once that has been worked out.

**Comment by chrisgraf** [comment]
seems to be a duplicate of #25 so closing this and keeping #25 for reference
