### ISSUE TITLE
Further investigate how the player should be managed

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#253]
We were discussing if we still want a Singleton that manages the player or wheter the player itself reacts to different signals.

Many arguments for both sides, we left this for now but should decide that in the near future.

**Comment by kb173** [comment]
My suggestion for the server request problem:

![image](https://user-images.githubusercontent.com/18697097/108274525-4e145600-7175-11eb-9692-43e300c51bfa.png)

the CommunicationServer forwards the request to a specific request handler, which is a child node of the player. It sets the position value of its parent and returns a response for the CommunicationServer to send back to the requester.

**Comment by kb173** [comment]
I'd say we can close this since the server connection problem has been solved as suggested above, or is there still something that's not clearly decided @MathiasBaumgartinger?

**Comment by MathiasBaumgartinger** [comment]
Should be closable
