### ISSUE TITLE
Make the World-Viewport splitable 

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#256]
Make the World-Viewport splitable, and then make each individual one configurable on it's own (Camera Position/Projection, Rendered Layers, ...)

https://www.youtube.com/watch?v=bf5NbS6HZ6c

![grafik](https://user-images.githubusercontent.com/33001106/111391808-a3308280-86b5-11eb-9ec1-a3782cc969ce.png)

**Comment by kb173** [comment]
Limiting this to the minimap for performance reasons (multiple fully-rendering viewports is not really feasible)

**Comment by chrisgraf** [comment]
is this related to the compare-view where two different states of the same view are compared?

**Comment by kb173** [comment]
With Godot 4.0, we probably just want to use OS-native windows for this rather than a custom Godot UI solution.

**Comment by kb173** [comment]
Rendering overhead is too large and we have no specific use-case, so closing
