### ISSUE TITLE
significant performance drop when clouds are shown

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#26]
![image](https://user-images.githubusercontent.com/1245084/57246524-c4e26c80-703d-11e9-9c11-9180ad94375c.png)

fps drop from 60 to 8!

**Comment by chrisgraf** [comment]
it is currently considered non-critical (we will investigate that for 0.4)

**Comment by kb173** [comment]
The clouds are computed by a ray-marching shader, which is very GPU-intensive. I've noticed that integrated (laptop) GPUs don't like displaying them at all, whereas a reasonably good graphics card doesn't have too big of a problem with them.

There are some tricks that can be applied to make ray-marching shaders more performant - we can revisit this in the future.

**Comment by chrisgraf** [comment]
we will test that on the new PC

**Comment by chrisgraf** [comment]
performance on new PC is ok
