### ISSUE TITLE
Add module parameter to logger calls

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#260]
It can be hard to work with the logger output when looking for a specific event because of how extensive it is. Adding module parameters to categorize logging would be a big help in my opinion.  
example: `logger.debug("Vegetation done loading", "render")`

This would allow us to only print out the modules we're currently interested in, while at the same time saving everything into a logfile if needed, by setting varying output strategies.  
example: `logger.get_module("render").set_output_strategy(logger.STRATEGY_PRINT + logger.STRATEGY_FILE)`

(these module output strategy calls could be based on an external config file so it's easy to change them as needed.)

**Comment by chrisgraf** [comment]
logging modules are already implemented in the new version of logger.gd (which was updated already quite a while ago). Usage see CommunicationServer.gd

**Comment by kb173** [comment]
Right, but they aren't used except for a few small new sections of code (I've recently started adding it as well after seeing that the updated logger supports it).

What I meant with this issue is that we continuously update our code with that parameter in order to make it easier to work with the entire output.
