### ISSUE TITLE
VR output is too dark

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#264]
The VR output is noticeably darker than the output to the monitor when VR is off. (This is expected for the VR mirror view, but not for the view inside the headset.)

HDR is enabled; `keep_3d_linear` is on as recommended (but turning it off, which should result in an output that is too bright according to the docs, doesn't actually change anything).

Maybe it has something to do with some post-processing effects in the WorldEnvironment? e.g. the "Filmic" Tonemap setting - it's possible that it's not being applied in VR. If so, we need to find a workaround that makes it look as nice as on the monitor.

**Comment by kb173** [comment]
Yeah let's try it together at the institute sometime - it is pretty noticeable on the Index, but maybe it's just the different monitor or something... in that case, we could just increase the brightness in the environment settings.

**Comment by MathiasBaumgartinger** [comment]
Okay, I think I see your point. I don't really know where this is comming from though. It is indeed probably the new WorldEnvironment, as I have not experienced anything similar before.

**Comment by kb173** [comment]
No longer relevant with #298
