### ISSUE TITLE
integrate osm layers via overpass API and WMTS on the fly

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#265]
overpass:
this could be done with the python overpass API which requests the bounding boxes of the tiles .. data could be cached. for a first approach overpass api code can be entered
wmts:
can be done via python also maybe via gdal/geodot?

**Comment by kb173** [comment]
WMTS works out of the box with Geodot, e.g. like this:

```var ortho_data = Geodot.get_raster_layer("WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb")```

Overpass needs additional work

**Comment by MathiasBaumgartinger** [comment]
> WMTS works out of the box with Geodot, e.g. like this:
> 
> `var ortho_data = Geodot.get_raster_layer("WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb")`

@kb173 did this actually work? 🤔

**Comment by kb173** [comment]
@MathiasBaumgartinger Yes, you can test it pretty easily in the Geodot demo

**Comment by kb173** [comment]
Apparently Overpass API actually also works out of the box: https://lists.openstreetmap.org/pipermail/dev/2012-September/025593.html

**Comment by kb173** [comment]
Yes, this command works:

```ogrinfo -ro -al "/vsicurl_streaming/https://lz4.overpass-api.de/api/interpreter?data=%28node%2850%2E746%2C7%2E154%2C50%2E748%2C7%2E157%29%3B%3C%3B%29%3Bout%20meta%3B%0A```
