### ISSUE TITLE
Add Rendering-Options

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#266]
We argued that for the workshop predefined rendering options might be useful as different stakeholders might argue different opinions (harmless visualization, etc.), similarly to the Season/Datetime tool.

- Clouds
- Haze/fog
- Ambient light
- Switch between physical and standard godot sky
- Windmill rotation speed
- Windmill light
- Night mode with additional lights

**Comment by kb173** [comment]
Closing since all the options are implemented and field-tested
