### ISSUE TITLE
enhancement: preload tiles if memory is still available (until memory cap is reached)

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#27]
while there is still memory available there are holes in the heightmap displayed where there were no holes before .. is there freed something prematurely?

**Comment by chrisgraf** [comment]
![image](https://user-images.githubusercontent.com/1245084/57561168-7ceb7e80-738a-11e9-91a1-006ec5d86fc5.png)

I don't know it this is due to the same issue .. the tiles seem to be gone (the area of the wind plants was visited just some seconds before) ... if I move towards the wind plants suddenly the tiles reapear...

**Comment by kb173** [comment]
Unless I'm misunderstanding, this seems like the intended behavior - the setting "tile-spawn-radius" is currently set to 1 to speed up debugging. A radius of 1 tile means that the client tries to keep the 9 tiles around the player active, removing others which are further away.

**Comment by chrisgraf** [comment]
Ok. Can this be set to unlimited by default so that tiles are just freed when a memory cap is reached? We could make this parameter changeable in debug mode in the client

**Comment by kb173** [comment]
Currently tiles are spawned and removed based only on the distance to the player, so while possible, this would require some reworking in how tiles are created, prioritized and deleted.

**Comment by chrisgraf** [comment]
the buggy component of this issue seems to be partly resolved by now or covered by other issues like the problem, where the hightmap below the player's location is lost sometimes.

In the future we should implement some memory gap and cache the tiles until this cap is reached to provide smoother reloading of already known tiles
