### ISSUE TITLE
orientation of assets currently are not configurable

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#28]
pv and wind assets should be automatically orientated related to the location they are placed - windmills should have an orientation of the main wind direction, pv assets should be orientated to south but this may be modified in special locations (mountains, valleys, ..)

this is currently considered a minor issue and we investigate it in 0.4

**Comment by chrisgraf** [comment]
@cmikovits : we would need a wind (main) direction for a region to rotate the wind assets accordingly

**Comment by chrisgraf** [comment]
as discussed, wind turbines are always approximately orientated in the wind direction (configured within the scenario); PV is always orientated south (so the default placement of an PV asset should result in this orientation)

**Comment by kb173** [comment]
Done with a9f9d3e (windmills) and 4e9532a (PV).

As noted in the commit, I'm assuming a wind direction of 90° means wind is blowing from west to east. If this is incorrect, we may have to tweak it by negating and/or subtracting 180°.

**Comment by chrisgraf** [comment]
the assumption is fine - we will require it that way

**Comment by chrisgraf** [comment]
we still need valid main wind directions per scenario

**Comment by cmikovits** [comment]
Main Wind direction per Scenario (Wind direction is reported by the direction from which it originates):

Joglland: North-West (315°)
Kamptal: West-North-West (300°)
Nockberge: North-West (315°)

Best wishes.

**Comment by chrisgraf** [comment]
the default wind directions are added to the fixture in 2bdb150 and the test-server database so closing this .. thanks
