### ISSUE TITLE
Teleportation of the Player should always be on the ground

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#280]
As of now, when teleportinghe ``FirstPersonPC`` from the LabTable we end up at the position `Vec3(new_x, old_y, new_z)`. This can be problematic, when the y-position on new_x, new_z of the terrain is higher than the old position. Then we are stuck below the terrain once the collider has loaded. 

I think there are would be two sensible ways to circumvent this: 
1. Give the Player a public function which always teleports on TOP of the terrain (should be possible with the `PositionManager`; preferable this function should be declared in the `AbstractPlayer` such that it can be called on any player (even if they are exchanged).
2. Make the player always stick to the ground (A raycast `-ifty` to `ifty` that always places on collision) unless turned off

Personally I would highly prefer option number 1. @kb173 what do you think?

**Comment by MathiasBaumgartinger** [comment]
After discussion we decided to use a public function for ANY teleportation happening instead of directly setting the translation. This function always teleports on top of the terrain:

`teleport_player(x, z, y=null)`

**Comment by kb173** [comment]
fixed by https://github.com/boku-ilen/landscapelab/commit/7e0731e3b46a0e64bf704f981785c1daf9ca818e
