### ISSUE TITLE
Implement a `save current configuration as geopackage` optionality

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#300]
Right now, if altered via the UI, all configurations are lost once you close the landscapelab. Giving an additional possibility to - for instance - load an object layer via the UI and then saving it inside the geopackage would be beneficial. Doing small variations for different projects would be a lot less infuriating this way.

This could/might/should also include other configurations, such as daytime, available tools, etc.

**Comment by MathiasBaumgartinger** [comment]
This will probably also require some new features in Geodot @kb173

**Comment by MathiasBaumgartinger** [comment]
[3843812](https://github.com/boku-ilen/landscapelab/commit/3843812f5aa55142dad9cb5491cbdd01d4625740)
[cbe946c](https://github.com/boku-ilen/landscapelab/commit/cbe946c476203ce790bb35ed795212bf56865f3a)
[7b48cb8](https://github.com/boku-ilen/landscapelab/commit/7b48cb886550f5ec4118473e71dc24373d4ad15f)
[11bb9c3](https://github.com/boku-ilen/landscapelab/commit/11bb9c34637cf8a49e826d62939d941803214a93)

Above commits introduced a first version for saving a current configuration, i.e. add a serialization of layer compositions, add option in UI and behavior for pressing option.

https://github.com/boku-ilen/landscapelab/compare/3843812f5aa5...c78d8e02b5c2 moves the saving and opening options into a new class specifically designed for the access of an ll-config. This class makes it easier to open/save configuration from anywhere in the code without the knowledge of what was previously known as `LayerConfiguration.gd`

[0bb7974](https://github.com/boku-ilen/landscapelab/commit/0bb7974cbe47d32413afc887182f97018cd8074a) also makes dynamic saving of the vegetation paths possible. 

Thus, this issue is resolved with the exception of a small bug in the `GeoLayer` classes, where after the first access of a geolayer of the same dataset (`geo_layer.get_dataset().resource_path`) will not return anything useful. @kb173 any ideas?

**Comment by kb173** [comment]
Fixed by Geodot's `get_file_info()` functions
