### ISSUE TITLE
Implement a `save changes to geolayer` option

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#301]
When doing modifications on a geolayer, it would be useful to have the possibility to write those changes into the file behind.

**Comment by kb173** [comment]
Related to https://github.com/boku-ilen/geodot-plugin/issues/65

**Comment by MathiasBaumgartinger** [comment]
178c39a5dffe1b733dfecda6320b4415d91e1f52 adds a basic option for saving changes. @kb173 GeoRasterLayers  do not support saving for now. I suppose we should create its own issue.
