### ISSUE TITLE
Generalize buildings with layer system to also show placement areas (Feldschläge)

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#31]
sometimes it may be necessairy to configure the placement areas per asset (like for PV) .. we have to revisit this for 0.4

**Comment by chrisgraf** [comment]
we also may have to make the placement areas configurable per scenario

**Comment by chrisgraf** [comment]
@chrisgraf : implementation server-side (model change and new url request)
@MathiasBaumgartinger : implementation client-side (we need to change the method how to get the placement polygons)

**Comment by chrisgraf** [comment]
additionally give the user feedback if the placement of an asset is not allowed (crossed out; red)

**Comment by chrisgraf** [comment]
@hrralph : provide the new placement areas as a single Multipolygon covering all scenarios

**Comment by kb173** [comment]
With CSG you can subtract polygons from other polygons: https://godotengine.org/article/godot-gets-csg-support

Here you can see the format of the MultiPolygon json: https://stackoverflow.com/questions/43645172/geojson-multipolygon-with-multiple-holes

**Comment by kb173** [comment]
Since we can fully depend on the Lego board (which has multiple alternative solutions if the lego detection itself does not work), this is not necessary for now. Also, the meshes are extremely complex and we would need additional logic to simplify and clip them.

**Comment by MathiasBaumgartinger** [comment]
As @kb173 mentioned, this is a very performance heavy operation. We should further discuss this topic.

**Comment by kb173** [comment]
We will probably clip the polygon in the server or change how it is transmitted.

**Comment by chrisgraf** [comment]
when we try to load custom geodata we will reintroduce the problem of nested polygons. We should start this discussion in the near future

**Comment by MathiasBaumgartinger** [comment]
With all the refactoring to our new layersystem, a system like this can be done more easily. Our thought here was to use the same layer-structure buildings use but make walls transparent and give it no roof. 

In an additional step this should also make this area "clickable"

**Comment by kb173** [comment]
Replaced by #287
