### ISSUE TITLE
Wind speed is not properly applied everywhere

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#315]
The vegetation does not seem to react (correctly) to a change in wind speed via the UI. Might be something that's not wired up correctly, or values which are not scaled well

**Comment by MathiasBaumgartinger** [comment]
It appears this issue slid back into our project as described above.

**Comment by MathiasBaumgartinger** [comment]
Fixed via [7104f2f](https://github.com/boku-ilen/landscapelab/commit/7104f2f584f940631087bc67895b0b3124e6ffd5)... closing
