### ISSUE TITLE
performance: unknown performance drop after some time running

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#33]
![image](https://user-images.githubusercontent.com/1245084/57322668-5caa8e00-7104-11e9-90c0-55f583bd9fac.png)
After approx 20min running without touching any controls the fps dropped from 60 to 8-15 fps for approx 1 minute before recovering again

**Comment by kb173** [comment]
If you notice this again, can you check whether any other parameters in the debugger changed during this fps drop?

**Comment by kb173** [comment]
We should leave the program running for some hours at some point and check this again.

**Comment by chrisgraf** [comment]
we should do this test some time but as the underlying structure changed quite a lot and this behavior is very strange I am leaning towards closing this issue
