### ISSUE TITLE
MinimapIcon's reset_rotation sometimes crashes the client

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#35]
With many assets, there seems to be a small chance for the following crash shortly after loading up the world:

```Attempt to call function 'reset_rotation' in base 'previously freed instance' on a null instance.```

It seems that sometimes, when `reset_rotation` is called in the MinimapIcon's `_process`, the node no longer exists. Since we don't seem to be deliberately freeing these nodes anywhere, I assume that this is because something else causes the node to crash?

Within the first two seconds or so after starting the world, some of the icons also rapidly spin one or several times. The crash (only!) happens during this time, while some icons are spinning. Could that be related?

**Comment by kb173** [comment]
The error can also happen inside `reset_rotation`:

```Attempt to call function 'get_global_transform' in base 'previously freed instance' on a null instance.```

Referring to this line:

```var angle = Vector3(1,0,0).angle_to(forward.get_global_transform().origin - get_global_transform().origin)```

Strangely, when looking at the variables in the debugger after the crash, both `self` and `forward` appear to be valid nodes...

**Comment by chrisgraf** [comment]
I am not sure if the debugger gets updated correctly in case of a crash

**Comment by MathiasBaumgartinger** [comment]
Commit 96a685c should fix this problem.
