### ISSUE TITLE
somethimes CachingImageTexture.gd:_load_into_dict() is called with null as parameter

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#38]
maybe this is also related with releasing a tile too early from memory?

**Comment by kb173** [comment]
With e8c3a21, this is fixed for me (I now get a more descriptive error saying that the VegetationModule didn't get some paths in a certain URL, which can happen with our incomplete data).

**Comment by chrisgraf** [comment]
Konstantin is working on the Vegetation data afaik .. is it easy to provide dummy data in the fixtures to prevent errors related to missing vegetation data for now? If not we wait for the reworked data...

**Comment by kb173** [comment]
I think that'd be a bit of work - we should hopefully have the real data soon, so I'd say we wait for that.

Can the issue be closed, since this case is now handled properly with descriptive error messages?

**Comment by chrisgraf** [comment]
ok :) .. closing it
