### ISSUE TITLE
Decide on code documentation conventions and make all documentation coherent

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#42]
Currently, most functions are documented like this:

```
# Does X by Y
func do_x():
    ...
```

And most nodes are documented like this:

```
extends Spatial

#
# Uses X to display Y
#
...
```

However, Godot also supports python-style docstring documentation, which is used in some places such as the ServerConnection script:

```
func do_x():
    """Does X by Y"""
    ...
```

We should decide on one of these conventions and make all current documentation coherent with that decision. Perhaps it would be good to research some possibilities to generate documentation from such comments, or recommendations from other big projects.

**Comment by chrisgraf** [comment]
I terms o readability I prefer the first approach much more .. is there any advantage of docstring? especially in the context of GodotScript?

**Comment by kb173** [comment]
No, docstrings offer no advantage - they simply evaluate to `true` and are ignored.
If you prefer that, we can decide to stick to the first approach. :+1:

**Comment by chrisgraf** [comment]
I think we agreed currently to the default documentation style and not use docstrings .. so we can close this. If something is unclear in this regard we will discuss it in discord.
