### ISSUE TITLE
the display of the splatmap (probably because of the water) is wrong

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#44]
![image](https://user-images.githubusercontent.com/1245084/58094461-07c14a00-7bd1-11e9-9bb1-822c72d05ef9.png)

- there are black pixels in the 3rd person view
- it gets rendered in the map view

**Comment by kb173** [comment]
It seems like transparency is a common issue between different graphics drivers, and this is such a case... It looks fine on my machine, but apparently transparency just becomes black on yours. In 5b286a8, I made a change that is recommended in situations with such issues, can you check whether this fixes it for you? 

The water has been removed from the minimap render layer, so the second point should be fixed.

**Comment by chrisgraf** [comment]
ok i will monitor if this flickering still exists

**Comment by chrisgraf** [comment]
and thanks for the fix of the latter

**Comment by chrisgraf** [comment]
flickering did not reappear again .. seems fixed
