### ISSUE TITLE
random crash of the gfx driver freezes pc

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#45]
After the following kernel messages a reset was necessairy .... a similar problem once occured also on windows with the nvidia driver ... should we escalate to godot? I don't have any possibility to make this reproducable 

May 21 16:11:38 localhost kernel: [419804.916824] radeon 0000:01:00.0: ring 0 stalled for more than 10240msec
May 21 16:11:38 localhost kernel: [419804.916836] radeon 0000:01:00.0: GPU lockup (current fence id 0x0000000000b9a75d last fence id 0x0000000000b9a771 on ring 0)
May 21 16:11:38 localhost kernel: [419804.916870] radeon 0000:01:00.0: failed to get a new IB (-35)
May 21 16:11:38 localhost kernel: [419804.916885] radeon 0000:01:00.0: failed to get a new IB (-35)
May 21 16:11:38 localhost kernel: [419804.916953] [drm:radeon_cs_ioctl [radeon]] *ERROR* Failed to get ib !
May 21 16:11:38 localhost kernel: [419804.916957] radeon 0000:01:00.0: failed to get a new IB (-35)
May 21 16:11:38 localhost kernel: [419804.917010] [drm:radeon_cs_ioctl [radeon]] *ERROR* Failed to get ib !
May 21 16:11:39 localhost kernel: [419805.513174] radeon 0000:01:00.0: Saved 1385 dwords of commands on ring 0.
May 21 16:11:39 localhost kernel: [419805.513199] radeon 0000:01:00.0: GPU softreset: 0x000000ED
May 21 16:11:39 localhost kernel: [419805.513201] radeon 0000:01:00.0:   GRBM_STATUS               = 0xA04C11A0
May 21 16:11:39 localhost kernel: [419805.513202] radeon 0000:01:00.0:   GRBM_STATUS_SE0           = 0x08000002
May 21 16:11:39 localhost kernel: [419805.513202] radeon 0000:01:00.0:   GRBM_STATUS_SE1           = 0x08000002
May 21 16:11:39 localhost kernel: [419805.513203] radeon 0000:01:00.0:   SRBM_STATUS               = 0x200046C0
May 21 16:11:39 localhost kernel: [419805.513220] radeon 0000:01:00.0:   SRBM_STATUS2              = 0x00000000
May 21 16:11:39 localhost kernel: [419805.513221] radeon 0000:01:00.0:   R_008674_CP_May 21 16:16:26 localhost systemd-modules-load[438]: Inserted module 'lp'

**Comment by kb173** [comment]
Searching for this yields some results, they all seem to be referencing the Linux kernel:
https://forums.linuxmint.com/viewtopic.php?t=197765
https://bugs.archlinux.org/task/50397
http://linux-kernel.2935.n7.nabble.com/radeon-0000-02-00-0-GPU-lockup-CP-stall-for-more-than-10000msec-td573671i20.html
https://bugzilla.kernel.org/show_bug.cgi?id=62721
There are also some recommended solutions there, e.g. a GRUB entry in the last link. Maybe it's not directly related to Godot... Perhaps you could try running a GPU benchmark or something like that for a while to check whether it crashes there as well?
If not, we could create a simple graphics-intensive Godot benchmark to see whether it's related to our specific program or Godot itself - and, if it's Godot itself, this program could be used for an issue at their GitHub repo.

**Comment by chrisgraf** [comment]
other crashes yielded different kernel logs .. but this could be a hardware problem too .. so I will investigate that further on my side ... unless it does not appear on another installation this does not concern me that much

**Comment by chrisgraf** [comment]
did not happen again on other gfx under linux so for now this was a hardware issue
