### ISSUE TITLE
vegetation creates holes in the ground

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#49]
![image](https://user-images.githubusercontent.com/1245084/58111963-c6419680-7bf2-11e9-9860-b9c00bce7910.png)

**Comment by kb173** [comment]
It seems like this is an issue with the heightmap shader - the problem is only visual, it's possible to walk over these holes normally. Perhaps it is related to the images being very small at that zoom.

**Comment by kb173** [comment]
Fixed by 935be73 - the problem was that VegetationModules were changing the flags of the heightmap image, which also affected the heightmap used in the shader, since both just held a reference to the same ImageTexture in the cache.
