### ISSUE TITLE
skybox in 3rd person view needs to be reworked

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#50]
the horizon of the skybox does not match the real horizon

**Comment by kb173** [comment]
A note about this: Setting the 'Sky Custom Fov' in the Environment seems to do something in that direction, but I've previously noticed that this should definitely be avoided with VR - it seems to change the depth of the sky, making it very confusing to look at.

**Comment by chrisgraf** [comment]
this might not be an issue if we have more tiles - receck later
