### ISSUE TITLE
terminating the program results in stacktrace

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#51]
klicking the stop button in the editor or the close button of the window currently closes the program but also issues a signal 11 (segmentation fault) and results in a stacktrace in the logs .. We need to confirm if this also happens in an exported project

**Comment by kb173** [comment]
This could be due to multiple threads still waiting for server requests being killed suddenly. We might want to implement our own 'Quit' functionality which waits for all active threads to finish.

**Comment by chrisgraf** [comment]
this still happens

**Comment by kb173** [comment]
Godot issue 33054 is about this, it's scheduled for 4.0. I'd say we just wait for that, since this issue doesn't really have negative effects for us other than seeming a bit unclean.

**Comment by kb173** [comment]
Does not seem to happen anymore, likely thanks to the rewrite of multithreaded loading with the layer system
