### ISSUE TITLE
Lifetime of vegetation particles is not infinite

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#52]
In 4e141f4, the vegetation particles were changed to one-shot because it solved an issue with flickering particles on some graphics drivers. However, Godot's particle system doesn't allow for particles to exist forever, so they will technically disappear at some point. 

They now live for 1661992960 seconds, which is the maximum. Realistically, this should never become a problem, but it's a bit hacky.

The Godot issue for this problem is 18117 - we should keep track of it.

**Comment by chrisgraf** [comment]
the godot issue got closed as unresolved. until godot supports 64bit that seems to be the limit. closing this, as 30+yrs runtime for the landscapelab is not a considered scenario
