### ISSUE TITLE
Follow mode: Ability to toggle if perspective are independent of each other or not

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#53]
With follow mode activated, one main perspective should determine the position on all others. Otherwise, all perspectives should be able to move independently of each other.
However, even with follow mode deactivated, there will have to be one main perspective which is the one which sets the global player position, which is e.g. used for where to split the LOD terrain.

With follow mode off, it would also be nice to see the positions of the other perspectives (e.g. as an icon).

**Comment by MathiasBaumgartinger** [comment]
This now works between PC/FirstPerson.tscn and PC/ThirdPerson.tscn. The FirstPerson will always set the global playerposition. I would need to discuss how exactly this should work for further implementation.

**Comment by MathiasBaumgartinger** [comment]
Everyone can control the position, but it will be permanently changed for every perspective to that point on follow mode enabled.

**Comment by MathiasBaumgartinger** [comment]
Basically works as intended now: 

A new abstract class from which all perspectives inherid holds the required functionalities for working with follow enabled/disabled.
If the follow mode is enabled, every perspective will listen to the coordinates of the global PlayerInfo. If a perspective moves, it sets the new position.

Only problem is that there is still a bug, as the first person sometimes glitches through the terrain. Will need further investigation to see why this is a problem.

**Comment by chrisgraf** [comment]
As discussed some days ago: 
if the follow mode is enabled the global position should be centered in both, the map view and the 3rd person view if they are enabled. Looking around in the 3rd person view (while the player stays in the center) should still be possible.
If the follow mode is disabled the 3rd-person view and the map view should be independent of the global position. Looking around should be possible, the global position is still represented by a marker. The LOD is currently not updated in these views but depends only on the global position (1st person view)

**Comment by chrisgraf** [comment]
a player symbol in the 3rd person view indicating the global position should be added

**Comment by chrisgraf** [comment]
for the terrain glitches there is another issue open for 0.4

**Comment by chrisgraf** [comment]
works as intended .. moving this to version 0.4 .. as soon as the player symbol was added to the 3rd person view this can be closed

**Comment by kb173** [comment]
Should be fixed in https://github.com/boku-ilen/landscapelab/commit/0dd43b36a1aa5de689f70ffa93c49bfe36851a76, will verify

**Comment by kb173** [comment]
The marker should work as expected with 15ba71a. It now always reflects the global player position from PlayerInfo.
