### ISSUE TITLE
Add ability to change speed in walk-mode

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#54]
This could be done with a slider in the UI.

**Comment by kb173** [comment]
The slider and its functionality have been added in 60014d4. The only thing left to do is to change the icon which shows the slider - it is currently identical to the Datetime button. @chrisgraf could you do this?

**Comment by chrisgraf** [comment]
can we add this to a submenu of the debug screen? so we do not need an icon for this and can also add other sliders for various setting parameters

**Comment by kb173** [comment]
Yes, that'd be no problem. Is it really only for debugging though? Seems like a feature which could be used more generally.

**Comment by kb173** [comment]
I moved the slider to the debug screen in 6e47842. Since it's a self-contained scene, we can easily move it somewhere else if we need to in the future.
