### ISSUE TITLE
step on the border of the tiles

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#57]
![image](https://user-images.githubusercontent.com/1245084/58753523-92068980-84c0-11e9-9407-8950e7c1e5e8.png)

**Comment by kb173** [comment]
To a small extent, this is unavoidable when a tile is next to a lower/higher LOD one. This does look too extreme though... Perhaps there is a slight error in calculating the offset and scale of the texture on the tile.

**Comment by kb173** [comment]
From what I can tell, this is pretty minimal in the new Geodot branch, likely due to better interpolation and exact tile cropping. It will be investigated more closely, but is probably fixed.

**Comment by kb173** [comment]
replaced by #240
