### ISSUE TITLE
Load and display GeoJSON multipolygons for assets

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#60]
First a request to load all the assets from the server needs to be implemented. These will fill the ui_controller.gd script. Once loaded when choosing an asset a GeoJSON multipolygon should be drawn to see where the asset can be placed. This will be shown until leaving the edit mode.

**Comment by MathiasBaumgartinger** [comment]
Components from server are now loaded into the json file.

**Comment by MathiasBaumgartinger** [comment]
Now does everything like it should, the problem is the itemSpawner gets set the according item id. For me locally the itemSpawner does not spawn items however.

**Comment by MathiasBaumgartinger** [comment]
Need placement arreas to continue with work.

**Comment by chrisgraf** [comment]
the real data is still in preparation .. can you add a dummy fixture?

**Comment by MathiasBaumgartinger** [comment]
````WorldPosition.get_position_on_ground(vec : Vector3)````

With this function the required y-axis for a given Vector3 with proper set x- and z-axis can be found.

**Comment by MathiasBaumgartinger** [comment]
Added dummy fixtures, will continue work once real data is there :)

**Comment by chrisgraf** [comment]
We probably need to enhance the given code to also cope with point data

**Comment by chrisgraf** [comment]
missing issue is the check if the overlay is above the surface

**Comment by chrisgraf** [comment]
this is moved and discussed further in #31 so closing this as duplicate
