### ISSUE TITLE
Replace the ThreadPool's queue with a priority queue

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#61]
Some server requests are more important than others - for example:
- Tiles which are far away do not need to be loaded as urgently as the tile next to the player
- Dynamic assets should be updated regularly, even if there are many other requests

Thus, a simple queue isn't the best data structure for the ThreadPool requests - it should be extended to be a priority queue instead.

We can then add a default priority to the `ThreadPool.enqueue_task()` call, and add a higher priority in some places where it makes sense.

**Comment by kb173** [comment]
A naive implementation of such a priority queue has been added in b1dde15. It is, however, very slow once there many tasks in the queue.

Since the ThreadPool is accessed very frequently, I'm not sure if a typical priority queue should be used here - even ideal implementations have O(log n) complexity for inserting and/or removing.

We don't need much precision with our priority - perhaps it would be enough to reduce it to a few levels (such as 'low', 'medium', 'high', 'very high') and simply use 4 separate queues. This means that we would, at worst, need to check 3 queues for whether they are empty.

**Comment by kb173** [comment]
Sorry, misclicked

**Comment by kb173** [comment]
Another note about this: Thread workers immediately start working on a task once there is one available, and then they can't switch to another task. This means that when a low priority task is inserted, and a high priority task directly afterwards, the low priority task will still be done first.

We could probably work around this by doing it similarly to how I described in my previous comment, and also checking the high priority queues more frequently than the low priority ones.

**Comment by chrisgraf** [comment]
sounds reasonable! Let's do it with 3 or maybe 4 levels ... I think this would be sufficiant for now

**Comment by kb173** [comment]
With 30831c9a82e83cb885fae8f030290b19e0ec1e30, the number of priorities and the threads working on each priority can be specified - e.g. 5 threads on high priority, 3 threads on medium, 2 threads on low.

With a good balance between priorities, this works well. Even with many requests coming in at the same time, high priority tasks will have a thread worker ready quickly, ideally immediately if there aren't too many high priority insertions.

For something more precise, we would probably need deeper access to scheduling and a bigger rewrite; this should be good enough.
