### ISSUE TITLE
enhancement: prevent controls from the ui to go through to the main screen

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#62]
when using the controls of the ui the main perspective below also moves

**Comment by MathiasBaumgartinger** [comment]
Setting the ui elements mouse options to stop does not work.

**Comment by MathiasBaumgartinger** [comment]
Check if this is fixable
Open godot-issue.

**Comment by kb173** [comment]
Likely also related to my comment at #48

**Comment by kb173** [comment]
After some testing, it seems like it is related, and solving #48 will solve this too. Closing this one as a duplicate
