### ISSUE TITLE
Refractor: First-Person and VR-Player are the setting PlayerInfo-Positions - the rest are Perspectives

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [boku-ilen/landscapelab#65]
Only the two main positions (FirstPerson, VR) set the global PlayerInfo's position, these will always set this position no matter the state of follow-enabled (VR and FirstPerson are basically the same). These are synchronized. If the follow-mode is disabled the other perspectives can be moved. If it gets enabled those perspectives should be updated with the global PlayerInfo's position and should not take input.

**Comment by chrisgraf** [comment]
VR1stPerson and PC1stPerson set the global Player postion mutally exclusive. There is always a global player position which is always shown in the other perspectives (Map, 3rd-Person view) 
If VR mode is active the player position is controlled via the VR input mainly (only optional teleportation etc can be done on the PC)

**Comment by chrisgraf** [comment]
with 12fd124f6d2196f2940c04ef30d294ce07532031 movement and looking around is disabled in 1st person view if vr_mode is active

**Comment by chrisgraf** [comment]
global player position is always shown
