### ISSUE TITLE
Assets get reset by the server when dragging

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#66]
The DynamicAssetHandler keeps assets in sync with their state on the server. It currently always sets them to their server position, the client can't change the position. Thus, when dragging an asset, it always gets reset to the position it has on the server.

The communication should work both ways. When dragging, the client might want to 'disconnect' the asset from the server, and then set the new position to the server once the dragging is done.

**Comment by kb173** [comment]
Assets are also currently never removed. We need to check whether an existing asset is in the newest server result, and remove it if it's not.

**Comment by chrisgraf** [comment]
updating from the server should only happen in lego mode and in the beginning .. all other changes are happening on the client anyways. this should cirumvent this issue

**Comment by chrisgraf** [comment]
the updating part is now fixed with 44b8ef24ccf72e16958273480276f6f8e1c8294c
still the removal needs to be implemented

**Comment by kb173** [comment]
Removal should be implemented, but needs to be verified and tested.

**Comment by kb173** [comment]
I can confirm that when an asset is deleted on the server, it is deleted on the client as well (as soon as an update happens). Of course this requires Lego mode to be turned on.
