### ISSUE TITLE
Offset in the land-use data

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#67]
It seems like the land use data is projected / positioned slightly differently than other raster data such as the orthophotos. It will likely have to be recalculated once we know exactly what the issue is.

**Comment by chrisgraf** [comment]
the offset for Nockberge seems -12, 35 (buildings to ortho)

**Comment by chrisgraf** [comment]
the local geodata seems fine this is an issue with projection or calculation within landscapelab!

**Comment by kb173** [comment]
What data did you look at? When comparing the same image file of land-use vs. orthophoto, they don't seem to completely align. The land-use data was exported with the projection setting "EPSG:3857", which should match the orthophoto, right?

**Comment by chrisgraf** [comment]
I compared our local othophotos with several other projected tiles and they all aligned correctly.

**Comment by chrisgraf** [comment]
this happens in gdal2tiles!

**Comment by chrisgraf** [comment]
@kb173 : this is corrected now, correct?

**Comment by chrisgraf** [comment]
correct
