### ISSUE TITLE
include a target energy value

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#68]
Implementation: @MathiasBaumgartinger 
Data: @cmikovits

**Comment by cmikovits** [comment]
on it

**Comment by chrisgraf** [comment]
added a preview of the energy target values in 67149573d63dfbc3bb83a319ee223c02c1a99bd7

**Comment by chrisgraf** [comment]
the UI needs to be updated on the client side: the target value needs to be placed next to the current energy value and has to change colors depending on exceeding the target value or not. Additionally a switch has to be added to change between summer, winter and average target value

**Comment by kb173** [comment]
The target value is in the scenario, you should be able to get it by something like `Session.get_current_scenario()["target_value_name"]`

**Comment by cmikovits** [comment]
notice: the data is still in discussion (also if we use different scenarios or just one single goal), winter, summer and whole year (average) will be delivered by me when the decision stands;
Dummyvalues for the moment from this document:

[generation.pdf](https://github.com/boku-ilen/landscapelab/files/3500841/generation.pdf)

**Comment by chrisgraf** [comment]
@MathiasBaumgartinger : we will wait for a final decision here - this is on hold

**Comment by MathiasBaumgartinger** [comment]
Implementation for value is there. Can also be changed for the according season. 

Color coding is still missing.

![image](https://user-images.githubusercontent.com/33001106/63697291-ebaaf580-c81c-11e9-94db-42ab60d5f56e.png)

**Comment by chrisgraf** [comment]
@MathiasBaumgartinger : we currently change this server side to an energy module
@chrisgraf : server side implementation of the sum per asset

**Comment by chrisgraf** [comment]
we will change the implementation according to current discussions #121 so closing this
