### ISSUE TITLE
Mutual exclusive asset placement with UI not working

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#69]
When the controller logo (top middle) is activated, assets should be placed locally in the client and NOT updated from the server.
When the Lego logo (top middle) is activated, assets are only updated from the server and can't be placed locally.

**Comment by chrisgraf** [comment]
fixed in b49f750fdc15a21f5bc421d11c3961f3c9eb45a2
Still open related to this: only poll lego coordinates when lego is enabled

**Comment by kb173** [comment]
This shouldn't be much more than an if-statement in the DynamicAssetHandler.

**Comment by kb173** [comment]
In 9ba2cfe, the DynamicAssetHandler got an option to only update when Lego mode is active (for windmills and PV). That should solve the issue.

Note that there won't be the familiar mass of windmills when starting the client now - they only appear once the Lego brick is clicked.

**Comment by kb173** [comment]
Actually, there seems to be an issue with the signal - it works at first, but deactivating the Lego brick again has no effect. Will investigate...

**Comment by kb173** [comment]
Actually completely solved now with c8421e3, it was just a typo.
