### ISSUE TITLE
Add rivers, streets into invekos land use tiles

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#70]
The rivers should be drawn into the land use tiles, so that they're displayed on the client.

**Comment by kb173** [comment]
I have tested the process of adding the rivers to the land-use data in a small area. I first increase the resolution of the land-use data and smooth it - otherwise, it would still have big pixels and stepped edges as opposed to the much finer detail of the river.

Smoothing:

1. Polygonize
2. v.clean
3. v.generalize with Snakes algorithm
4. Rasterize back (high resolution)

Adding river data:

1. Rasterize rivers
2. Set nodata to 0 with r.null
3. Raster calculator: ```("river_raster@1" != 60) * "low_bytes_clipped@1" + ("river_raster@1" = 60) * "river_raster@1"```

This writeup is just for documerntation purposes - I hope to turn it into a qgis script later, to make it more reproducable.

**Comment by kb173** [comment]
Smoothing and adding the rivers is done for the Nockberge region! It looks like this:

![landuse-smooth-with-river](https://user-images.githubusercontent.com/18697097/62427653-72752280-b6f6-11e9-98c5-628e097d90da.png)

@chrisgraf Where's the dataset with roads and their respective width? Then I could add those in as well before tiling. I tried `Infra_Untersuchungsgebiete/streets_webm.shp`, but those don't seem to have a width. Or do I need to turn it into polygons somehow to get visible width?

Hopefully, #67 will be fixed too when tiling this new data.

**Comment by kb173** [comment]
By the way, the polygonized and smoothed land-use data might be nice to save for the future as well (calculating those took quite long). Should I upload it to the ilen-q? It's about 1 GB for Nockberge.

**Comment by chrisgraf** [comment]
@kb173 : Put the data for all areas (if feasable) to a new subdirectory on ilen-q for further reference. The road width is in the attribute WIDTH (ask me directly for details)

**Comment by kb173** [comment]
The wiki now contains the detailed process for smoothing the land-use and adding polygon data. For Nockberge, the calculations are almost done and will be uploaded then. Since that's just a matter of waiting, I'd consider this closed.
