### ISSUE TITLE
Build framework for linear datasets (power lines)

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#71]
We'll need to parse linear data for power lines, streets, etc. We should build a framework which can be used for all this data, and extended depending on what exactly should be done with those lines.

For power lines, we'll place power poles and connect them with lines inbetween.

**Comment by chrisgraf** [comment]
For power lines and similar net data we require a model/table which links the connections to the nodes

**Comment by kb173** [comment]
Streets are now being displayed! There are still some things to do though - there's only one type of road at the moment, and the width isn't used in the client.

Also, the issue of keeping them perfectly level with the ground has to be solved properly - currently there's a workaround from 5f413f3 which usually works well, but can go wrong. Iterating over all points regularly isn't viable since it causes big noticeable stutters.

**Comment by kb173** [comment]
The other type of asset with linear data (e.g. for power lines) has been described more specifically in #96. Since roads have a basic implementation which works for the 0.4 demo, this can be closed. For the remaining problems, more specific issues will be created.
