### ISSUE TITLE
teleportation on PC screen does not yet work

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#74]
By clicking the teleport icon the teleport mode should be enabled. This means 
- the mouse pointer should change and by clicking anywhere in the two perspectives the position of the first person view should change to the position
- a dropdown list of the points of interests (location_location) associated to the current scenario should be shown. Clicking on one of the POIs the position should be changed to the POI

If the VR mode is active aditionally a safety check should be displayed before the actual teleport

**Comment by chrisgraf** [comment]
status implemented: testing needed

**Comment by kb173** [comment]
Will be implemented as a child of MousePoint so that the mouse logic does not need to be there

Would be nice to always have an indicator in the world where the mouse is currently pointing (e.g. glowing)

**Comment by MathiasBaumgartinger** [comment]
Feature is implemented, aswell as the indicator for the mouse position. I fear teleportation is a bit glitchy at times. Like mentioned in #89 testing for me locally is hard at the time.

**Comment by kb173** [comment]
Working, see #89 for details
