### ISSUE TITLE
missing feature: add a POI and switch between POIs

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#77]
This can be integrated into the teleport mode (see #74 )

**Comment by MathiasBaumgartinger** [comment]
Nice to have: Add and remove POIs

**Comment by MathiasBaumgartinger** [comment]
Points of Interest teleport functionality is implemented. With our Viewports-problem it is a little tricky and random if the double-click gets registered. Some points do not get loaded as the tiles are so far away that they cannot be found.

**Comment by MathiasBaumgartinger** [comment]
All points are loaded now; If tiles are too far away and not loaded yet the TileHandler will no longer return a 0-value.

**Comment by kb173** [comment]
Working with all PoIs for me! Judging from the town names in the minimap, the locations are correct as well.
