### ISSUE TITLE
Memory leak explosion caused by MinimapIcon

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#78]
When there are windmills far away from the origin, an explosion in memory usage can happen due to the pixel_size of their icons. This crashes the game at best, the whole PC at worst.

This has been reported to Godot (issue 31023).

As a workaround, we should add a check to only spawn nearby assets. How close they have to be should differ by asset_type.

**Comment by kb173** [comment]
A first workaround (hardcoded distance check) was added in 4771fdb. This should fix the crashes.

**Comment by chrisgraf** [comment]
is the workaround mentioned in https://github.com/godotengine/godot/issues/20855 usable in our case?

**Comment by kb173** [comment]
As someone wrote in 31023, it's a deep recursion in the engine, so the possibility of something happening with it is always going to be there until that's fixed. However, it should be practically impossible with our current systems because we always only load nearby assets.

I'd still keep this open though, just in case we run into it again with something else - finding out about this took some pretty extensive debugging...

**Comment by kb173** [comment]
Fixed by Godot! (see 31023)
