### ISSUE TITLE
steering the 1st person player should always be possible

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#80]
does currently not work if the 1st person perspective is not shown
can be implemented within the restructurement of the AbstractPlayer

**Comment by chrisgraf** [comment]
low priority, maybe in 0.4 else in future

**Comment by MathiasBaumgartinger** [comment]
Commit #e530f79 should have worked this out. Probably should be tested further as this could induce other problems. Will be a tagged with ``needs testing`` for now.

**Comment by kb173** [comment]
e530f79 made it impossible to control the 3rd person perspective... I think the 1st person player, which is now always active, fetches the input and flags it as handled.

Let's look at this again tomorrow (I reverted it on the workshop PC)

**Comment by MathiasBaumgartinger** [comment]
As mentioned by @kb173 this will probably not be implemented for 0.4. as it is a little more tricky than expected. Further discussion tomorrow.

**Comment by MathiasBaumgartinger** [comment]
As Tom told us this is not a very important feature we will move it to a later version.

**Comment by kb173** [comment]
Solved via #243
