### ISSUE TITLE
we have to limit the movement within the scenario bounding polygon

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#81]

**Comment by chrisgraf** [comment]
as the workshops are moderated we will postpone the implementation to a possible future

**Comment by MathiasBaumgartinger** [comment]
@chrisgraf maybe we can discuss this issue sometime in the future?

Questions:
- Is this still necessary?
- If yes is the case of the bounding polygon being a multipolygon with a hole inside of it important and should it be handled?

**Comment by chrisgraf** [comment]
this is a game mode specific issue and this game mode probably will not be needed in the same form. But similar issues could arise in the future with other game modes

But this general issue is tracked with #31 so we can close this
