### ISSUE TITLE
implementation of the energy details dropdown is still missing

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#84]
here we just list the assets with the aggregated energy data (sum)

**Comment by MathiasBaumgartinger** [comment]
After a discussion with @kb173 we came to the conclusion that the energy values should be handled on server-side. As the assets have a random energy value currently the server also will return a random value right now. We should consider making the random values a new issue in my opinion.

As of now we can get the values by using:

``/assetpos/energy_contribution/[asset_type].json`` returns all instances for a specific type.
``/assetpos/energy_contribution/all.json`` for all instances.

Both json-responses will return ``total_energy_contribution`` and ``number_of_asset``.

**Comment by MathiasBaumgartinger** [comment]
Implemented, we should discuss if types are enough or if each specific asset should be shown.

![image](https://user-images.githubusercontent.com/33001106/63695036-0e86db00-c818-11e9-8e46-905796981213.png)

**Comment by chrisgraf** [comment]
closed as the implementation of this changes #121
