### ISSUE TITLE
reduce necessairy clicks when selecting the asset to place in controller mode

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#85]
we currently just have three different assets which can be placed so we would prefer that these assets would be shown immediately as a suboption of the shown asset types after the controller UI button is pressed.
Currently we have to select the asset type and then the menu of associated assets are shown which leads to an additional click

**Comment by chrisgraf** [comment]
postponed as low priority

**Comment by MathiasBaumgartinger** [comment]
Implemented with commit #0e05d24. Closing ...
