### ISSUE TITLE
Refactor teleportation code

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#89]
Presumably due to #48, the teleport click can go through immediately and teleport to the position below the button.

**Comment by chrisgraf** [comment]
we want to introduce a short delay to prevent this as a workaround

**Comment by MathiasBaumgartinger** [comment]
A timer is implemented. Im not really sure if this fixed the issue, on my local machine (laptop) teleportation still seems a bit buggy. I cannot verify that this is only a local problem as my machine really has trouble running the application, however. Maybe someone can test this and give me a feedback.

**Comment by kb173** [comment]
With the two referenced commits, it's working for me now.

`remove_child` should be avoided - it removes the node from the tree, but not from memory. I believe some weird behavior was caused by new nodes being instanced, but old nodes remaining and actually still being referenced sometimes. `queue_free()` actually removes the node from both the tree and the memory as soon as it's safe to do so.
I personally like using `get_child(name)` instead of references in variables to make sure that the code is always in tune with how the tree actually looks - otherwise, you can get variables referencing unused nodes or memory leaks.
Getting children by index like `get_child(1)` should be avoided though, since they're fragile (the order of children isn't set in stone) and not very readable since you have to check what it's referencing in the other scene.

I think the performance could be improved by not loading the PoIs each time the button is clicked, but simply loading it once and hiding/showing it.

Leaving the issue open in case you want to refactor it a bit - the functionality should be fine, though.

**Comment by MathiasBaumgartinger** [comment]
Refactored the code, sorry for the ugliness :disappointed:
