### ISSUE TITLE
Trees on Streets

### ISSUE THREAD

**Issue by luxkon** [boku-ilen/landscapelab#94]
I went along a road and there appered trees on the street.

**Comment by chrisgraf** [comment]
@luxkon : spacing of street polygons should be 1-2m broader

**Comment by kb173** [comment]
Currently working on the new land-use data (with all regions), the new `streets_webm_ply2` will be used in the intersecting step, so this should be fixed once that data is done.

**Comment by kb173** [comment]
This is fixed in the land-use data for the 2 later regions, we'll keep the current data for Nockberge since it's not a big enough issue to redo the whole land-use
