### ISSUE TITLE
streets fragmented into several small parts

### ISSUE THREAD

**Issue by luxkon** [boku-ilen/landscapelab#95]
Some small Streets are just 50m long and not linked to other Streets. Maybe the other parts are under the Surface?

**Comment by kb173** [comment]
Yeah, I checked again and we definitely have some streets under the surface. Working on a general solution for keeping assets on the ground

**Comment by kb173** [comment]
Now that assets are properly kept on the ground, the streets mostly look good. However, they still sometimes intersect with the terrain a bit. I think this is due to the heightmap making too steep jumps due to them not being very precise - we can look at this again when we have the new heightmap.

**Comment by kb173** [comment]
We still rarely have streets under the surface. We probably need to overhaul the relationship between terrain and streets to completely fix this...

**Comment by kb173** [comment]
Fixed by the redesign (#168)
