### ISSUE TITLE
Implement Layer type 'Connected Object'

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab#96]
Currently, we have normal assets (which just have a position, e.g. wind turbines) and linear assets (which are extruded from a line, e.g. roads). We need an additional type that is similar to a normal asset, but has connections to other assets. An example where this is required are power lines: The poles are normal assets, but each pole can be connected to any number of other poles. These connections are displayed as power lines.

This means that these assets will probably have two additions: The next assets (n-to-n-relationship to other Connected Assets) and how the connection should be displayed (maybe a texture that is stretched and/or repeated).

**Comment by chrisgraf** [comment]
we have to prepare this now somehow directly in the geopackage

**Comment by MathiasBaumgartinger** [comment]
Related to  #231, will probably close and reopen this issue in a unified standard with other types.

**Comment by kb173** [comment]
Closing since this type of layer has been implemented and is being successfully used for visualizing power poles
